# Generated by Django 5.0.6 on 2024-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
