# Generated by Django 5.0.6 on 2024-05-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('translated_content', models.TextField()),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.languages')),
            ],
            options={
                'db_table': 'translations',
            },
        ),
    ]
