# Generated by Django 5.0.6 on 2024-05-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_rename_languages_language'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
