# Generated by Django 5.0.6 on 2024-05-27 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0001_initial'),
        ('translations', '0002_alter_translation_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaries.diary')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
    ]
