# Generated by Django 5.0.6 on 2024-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
